# Memory for the Minecraft decompilation / recompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
# NeoForge for 1.20.1 (https://maven.neoforged.net/releases/net/neoforged/forge/)
neo_version=47.1.106
neo_version_range=[47.1,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties

mod_id=betterenddragon
mod_name=Better End Dragon
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.lrbkdgw.betterenddragon
mod_authors=lrbkdgw
mod_description=Four power crystals, a two-phase super Ender Dragon and the Underworld dimension.
pack_format_number=15
